# Generated by Django 2.1 on 2018-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=32)),
                ('ip_addr', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('sn', models.CharField(max_length=32)),
                ('local', models.CharField(max_length=32)),
                ('resource_type', models.CharField(max_length=32)),
                ('port', models.DecimalField(decimal_places=0, max_digits=8)),
                ('system_version', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=16)),
            ],
        ),
    ]
